sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 6
  - 6.1
before_install:
  - npm i -g npm@^3.0.0
before_script:
  - npm prune
script:
  - npm test
  - npm run cover
after_success:
  - npm run report-coverage